name: promise_with_me_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: jua
      fonts:
        - asset: assets/fonts/bm_jua.otf